package app

import (
	"encoding/json"
	"log"
	"net/http"
	"strconv"
	"time"

	httpSwagger "github.com/swaggo/http-swagger"

	"ecomm/api-gateway/internal/admin"
	hc "ecomm/api-gateway/internal/health"
	"ecomm/api-gateway/internal/proxy"
	"ecomm/api-gateway/internal/registry"
	"ecomm/api-gateway/internal/util"
)

// Options configures the API Gateway HTTP server wiring.
type Options struct {
	Port           string
	Repo           registry.Repository
	Registry       *registry.Registry
	JWTSecret      string
	HealthInterval time.Duration
}

// NewServer builds the http.Server with all routes and background jobs wired.
// It assumes migrations and repository initialization are already done by the caller.
func NewServer(opts Options) (*http.Server, error) {
	if opts.Port == "" {
		opts.Port = "8080"
	}
	if opts.Registry == nil {
		opts.Registry = registry.New()
	}
	if opts.HealthInterval <= 0 {
		opts.HealthInterval = 30 * time.Second
	}
	// Load enabled services into in-memory routing registry
	if opts.Repo != nil {
		if err := registry.LoadEnabled(opts.Repo, opts.Registry); err != nil {
			log.Printf("warn: load registry failed: %v", err)
		}
	}

	mux := http.NewServeMux()

	// System health endpoints
	mux.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"status": "ok"})
	})
	mux.HandleFunc("/readyz", func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		_ = json.NewEncoder(w).Encode(map[string]any{"status": "ready"})
	})

	// Public proxy surface
	mux.HandleFunc("/api/", proxy.Dynamic(opts.Registry))

	// Admin API with middleware chain
	adm := admin.NewHandler(opts.Repo, opts.Registry)
	adminChain := util.Chain(util.CORSv2(), util.JWTAuthV2(opts.JWTSecret))
	mux.Handle("/admin/services", adminChain(http.HandlerFunc(adm.Services)))
	mux.Handle("/admin/services/", adminChain(http.HandlerFunc(adm.ServiceByID)))

	// Swagger UI generated by swaggo at /swagger/index.html
	mux.Handle("/swagger/", httpSwagger.WrapHandler)

	// Start background health checker
	if opts.Repo != nil {
		sec := int(opts.HealthInterval / time.Second)
		if sec <= 0 {
			sec = 30
		}
		hc.Start(opts.Repo, strconv.Itoa(sec))
	}

	srv := &http.Server{Addr: ":" + opts.Port, Handler: mux}
	return srv, nil
}
